apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehicle-rentals-app
  namespace: vehicle-rentals
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vehicle-rentals-app
  template:
    metadata:
      labels:
        app: vehicle-rentals-app
    spec:
      containers:
        - name: php-apache
          image: akash00121/vehicle-rentals-app:v1
          ports:
            - containerPort: 80
          env:
            - name: DB_HOST
              value: "mysql"
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_DATABASE
            - name: DB_USER
              value: "root"
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: vehicle-rentals-service
  namespace: vehicle-rentals
spec:
  type: NodePort
  selector:
    app: vehicle-rentals-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080

